name: Build and publish to NPM on push to master

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Changeset version
        id: version
        run: |
          pnpm changeset version
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish and commit version bump
        if: steps.version.outputs.no_changes == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm run build
          
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          
          pnpm publish --access public --no-git-checks
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add package.json CHANGELOG.md
          
          git commit -m "chore: release new version [skip ci]" || echo "No changes to commit"
          
          git push origin HEAD:master
